### ISSUE TITLE
Unable to understand API key

### ISSUE THREAD

**Issue by laymanstake** [dfinke/PowerShellAIAssistant#10]
When I run the command to create assistant then it fails

02/02/2024 09:03:37 | C:\Users\Admin: 0.04 seconds PS>$assistant = New-OAIAssistant
Invoke-OAIBeta: C:\Users\Admin\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.6\Public\New-OAIAssistant.ps1:72
Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: ''. You can find your API key at https://platform.openai.com/account/api-keys.
02/02/2024 09:05:14 | C:\Users\Admin: 0.36 seconds PS>$env:OPENAI_API_KEY
sk-**********************3y

**Comment by dfinke** [comment]
Thanks for trying the `PowerShell AI Assistant`

Sorry you need to set this `$env:OpenAIKey`

**Comment by asheroto** [comment]
Ah, this helped me too. Going to submit a PR for a few files I see that need updating.

**Comment by dfinke** [comment]
@asheroto Thanks for trying PowerShell AI Assistant.

Thank you for the PRs. Working to get to them today. I'll be away till mid-week if not.

**Comment by dfinke** [comment]
@asheroto good to go. Thank you again! Will publish it. 
You're on all the socials except X?

**Comment by asheroto** [comment]
Glad I could help! 😊

I don't really much with social media right now. A mini summary of my background is on [asheroto.com](https://asheroto.com), though.

Thanks so much for the invite! I plan on attending!

**Comment by gpehlev** [comment]
I am still getting an error fetching the API key with both variable names - _$env:OpenAIKey_ and _$env:OPENAI_API_KEY_. I refreshed the environment variables using @asheroto's script: https://github.com/asheroto/Refresh-EnvironmentVariables/blob/main/Refresh-EnvironmentVariables.ps1.

**Comment by asheroto** [comment]
In PowerShell if you just type...

~$env:OpenAIKey = "your api key"~

And then try it, does it work?
