### ISSUE TITLE
add -Proxy parameter for New-OAIAssistant

### ISSUE THREAD

**Issue by Davider-code** [dfinke/PowerShellAIAssistant#19]
my System: windows 10 Pro 21H2, Powershell 5.1

I'm a novice in PowerShell. The network I'm using cannot directly access the ChatGPT API. I need to use a proxy for access. However, when using the following code, I don't receive any response.

```
$env:http_proxy = "http://127.0.0.1:1081"
$env:https_proxy = "http://127.0.0.1:1081"
$env:OpenAIKey = 'sk-XXXX'
$assistant = New-OAIAssistant -Debug

# Comment: Output the details of the $assistant object
$assistant
```

Therefore, I hope to add a **-Proxy** parameter, just like below, so that I can successfully use the following code to install the module
```
Install-Module -Name PSOpenAI -Force -Proxy "http://127.0.0.1:1081"
```

**Comment by dfinke** [comment]
Interesting. I have not played with proxies. Need to look to see if Invoke-Restmethod supports it. That is what is under the covers.

What is the error you get?

**Comment by Davider-code** [comment]
> Interesting. I have not played with proxies. Need to look to see if Invoke-Restmethod supports it. That is what is under the covers.
> 
> What is the error you get?
After waiting for approximately 30 seconds, the following prompt appeared, likely due to a failed proxy connection
```
Test-JsonReplacement: Cannot bind argument to parameter 'JSON' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellAIAssistant\0.2.0\Private\Invoke-OAIB
eta.ps1:122 char:38
+             if (Test-JsonReplacement $message -ErrorAction SilentlyCo ...
+                                      ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-JsonReplacement]，ParameterBindingValidati 
   onException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-JsonReplacem 
   ent
```

**Comment by Davider-code** [comment]
> Interesting. I have not played with proxies. Need to look to see if Invoke-Restmethod supports it. That is what is under the covers.
> 
> What is the error you get?

The issue was resolved using the following code. It would be more convenient if this functionality were implemented in the '-proxy' parameter.
```
[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebProxy]::new('http://127.0.0.1:1081/')
$assistant = New-OAIAssistant -Debug
# Comment: Output the details of the $assistant object
$assistant
```

**Comment by dfinke** [comment]
Thanks for tracking that down. Need to think where to "enable" that.

I'm guessing if you do not set the `DefaultWebProxy` and try `Get-OAIAssistant`, it will fail. So the DefaultWebProxy` needs to be a module level variable.
