### ISSUE TITLE
New-OAIMessage does randomly stops responding

### ISSUE THREAD

**Issue by Xentraxx** [dfinke/PowerShellAIAssistant#21]
The New-OAIMessage can fail, run successfully but also there is an undesired behaviour where there is no output and my script is just stuck at this point indefinitely. This happens at different iterations, randomly with different input, so I assume the issue is, that there is a timeout and nothing reacts to that.
To be concrete, I think the issue is, that in the Invoke-OAIBeta.ps1, in line 117, the ConnectionTimeoutSeconds parameter is not set.
Could you please verify that behavior?

**Comment by Xentraxx** [comment]
I just increased the delay between the invocations of New-OAIMessage which seems to help.

**Comment by Xentraxx** [comment]
I do use OpenAI as a provider and wait 35 seconds between a run and posting a new message. Not always enough, but at least it fails and I catch the error and try again until the run finished successfully and I can post a new message.
That way the script hasn't been stuck anymore, even after more than 180 iterations.
I think it would greatly enhance the usability if the New-OAIRun command would be asynchronous, so you don't have to catch errors and create loops with sleep statements to run one message after another.

**Comment by Xentraxx** [comment]
Not perfect, but here is the reveant part of my little script:
`do {
            $isThisElementPending = $false
            try {
                Write-Output "Will try to add message to Thread"
                New-OAIMessage -ThreadId $thread.id -Role "user" -Content "$goal,$helptext" -ErrorAction Stop | Out-Null
                for ($i = 35; $i -ne 0; $i--) {
                    Write-Host "$i from 35 seconds remaining. Question: $($element.ID)"
                    Start-Sleep -Seconds 1
                }
            }
            catch [Exception] {
                Write-Host "An error occured with $($element.ID)! Retrying in 30 seconds!" -ForegroundColor Red
                $isThisElementPending = $true
                for ($i = 35; $i -ne 0; $i--) {
                    Write-Host "$i from 35 seconds remaining. Question: $($element.ID)"
                    Start-Sleep -Seconds 1
                }
            }
        }while ($isThisElementPending)`

**Comment by Xentraxx** [comment]
I've tried to set them and still had issues. I came to the conclusion that it is not the root problem.

**Comment by dfinke** [comment]
Thanks for letting me know. I suspected it is OpenAI's side. I have an Azure OAI setup. The PS functions stall there also. It ususally is an Azure "issue". While this is still and beta and Microsoft is still onboarding all the new bits, I'm going to wait.

It is annoying and there are still tons of things to learn about the API that is now in PS. Plus, the service comes back relatively quickly.
