### ISSUE TITLE
Question: Starting - stopping Threads

### ISSUE THREAD

**Issue by RStadlmair** [dfinke/PowerShellAIAssistant#5]
Hi Doug! 

Just tested, based on your [example](https://github.com/dfinke/PowerShellAIAssistant/blob/main/examples/Assistants_API_overview.ipynb). 

To make an assistant an integrated part of my day-to-day PowerShell experience in the console, i was just wondering if it is a good strategy to create a "Powershell Expert Assistant" in my PowerShell profile.

Question: Is it best practice to simply create a new Assistant and a Thread for each new session so that i can ask questions to it ?

R.

**Comment by dfinke** [comment]
Thanks for trying the module @RStadlmair. Great questions.

You can create an assistant `New-OAIAssistant` once and the definition will remain in the cloud, till you delete it. In your profile you can use the assistant id in the call when you create a message on a thread.

You can then avoid creating an assistant each time you ask your assistant a question.

I'm working on an example for when you have a conversation with an assistant. More than a one-off question.

Then you continue to use the same thread, and add messages to it.

Hope that helps. Feel free to post more questions.

**Comment by RStadlmair** [comment]
That is for now the answer i was looking for. With more eamples and a guide on the other CmdLets i am sure to come along.
